//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fishing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fishing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --force-database-sync.
        /// </summary>
        internal static string ArgumentForceSync {
            get {
                return ResourceManager.GetString("ArgumentForceSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No_args.
        /// </summary>
        internal static string ArgumentNoArgs {
            get {
                return ResourceManager.GetString("ArgumentNoArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        internal static string ArgumentStart {
            get {
                return ResourceManager.GetString("ArgumentStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot fish here..
        /// </summary>
        internal static string ChatBadLocation {
            get {
                return ResourceManager.GetString("ChatBadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} caught .
        /// </summary>
        internal static string ChatFormatCaught {
            get {
                return ResourceManager.GetString("ChatFormatCaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} regretfully releases.
        /// </summary>
        internal static string ChatFormatInventoryFull {
            get {
                return ResourceManager.GetString("ChatFormatInventoryFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} caught a monster!.
        /// </summary>
        internal static string ChatFormatMonster {
            get {
                return ResourceManager.GetString("ChatFormatMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} obtains .
        /// </summary>
        internal static string ChatFormatObtains {
            get {
                return ResourceManager.GetString("ChatFormatObtains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} fishes up a large box.
        /// </summary>
        internal static string ChatFormatQuestBox {
            get {
                return ResourceManager.GetString("ChatFormatQuestBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} obtained the temporary item: .
        /// </summary>
        internal static string ChatFormatTempFish {
            get {
                return ResourceManager.GetString("ChatFormatTempFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You feel something pulling at your line..
        /// </summary>
        internal static string ChatHookItem {
            get {
                return ResourceManager.GetString("ChatHookItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something caught the hook!!!.
        /// </summary>
        internal static string ChatHookLargeFish {
            get {
                return ResourceManager.GetString("ChatHookLargeFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your line breaks..
        /// </summary>
        internal static string ChatHookLineBreak {
            get {
                return ResourceManager.GetString("ChatHookLineBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something clamps onto your line ferociously!.
        /// </summary>
        internal static string ChatHookMonster {
            get {
                return ResourceManager.GetString("ChatHookMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something caught the hook!.
        /// </summary>
        internal static string ChatHookSmallFish {
            get {
                return ResourceManager.GetString("ChatHookSmallFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You lost your catch..
        /// </summary>
        internal static string ChatLostCatch {
            get {
                return ResourceManager.GetString("ChatLostCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You lost your catch due to your lack of skill..
        /// </summary>
        internal static string ChatLostLackSkill {
            get {
                return ResourceManager.GetString("ChatLostLackSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are now docking in .
        /// </summary>
        internal static string ChatLostShipDock {
            get {
                return ResourceManager.GetString("ChatLostShipDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatever caught the hook was too large.
        /// </summary>
        internal static string ChatLostTooLarge {
            get {
                return ResourceManager.GetString("ChatLostTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatever caught the hook was too small.
        /// </summary>
        internal static string ChatLostTooSmall {
            get {
                return ResourceManager.GetString("ChatLostTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t fish without bait on the hook..
        /// </summary>
        internal static string ChatNoBait {
            get {
                return ResourceManager.GetString("ChatNoBait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your rod breaks..
        /// </summary>
        internal static string ChatRodBreak {
            get {
                return ResourceManager.GetString("ChatRodBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must wait longer to perform that action..
        /// </summary>
        internal static string ChatWaitLonger {
            get {
                return ResourceManager.GetString("ChatWaitLonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d_dark {
            get {
                object obj = ResourceManager.GetObject("d_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d_earth {
            get {
                object obj = ResourceManager.GetObject("d_earth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d_fire {
            get {
                object obj = ResourceManager.GetObject("d_fire", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d_ice {
            get {
                object obj = ResourceManager.GetObject("d_ice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d_light {
            get {
                object obj = ResourceManager.GetObject("d_light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d_thunder {
            get {
                object obj = ResourceManager.GetObject("d_thunder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d_water {
            get {
                object obj = ResourceManager.GetObject("d_water", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d_wind {
            get {
                object obj = ResourceManager.GetObject("d_wind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string DBSyncMessageDone {
            get {
                return ResourceManager.GetString("DBSyncMessageDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}:.
        /// </summary>
        internal static string DBSyncMessageFormatDownloading {
            get {
                return ResourceManager.GetString("DBSyncMessageFormatDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming {0} to {1}.
        /// </summary>
        internal static string DBSyncMessageFormatRenaming {
            get {
                return ResourceManager.GetString("DBSyncMessageFormatRenaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading {0}:.
        /// </summary>
        internal static string DBSyncMessageFormatUploading {
            get {
                return ResourceManager.GetString("DBSyncMessageFormatUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Sync....
        /// </summary>
        internal static string DBSyncMessageStart {
            get {
                return ResourceManager.GetString("DBSyncMessageStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Char similar to !.
        /// </summary>
        internal static char Exclamation {
            get {
                object obj = ResourceManager.GetObject("Exclamation", resourceCulture);
                return ((char)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Line Fish.
        /// </summary>
        internal static string FishNameBreakLine {
            get {
                return ResourceManager.GetString("FishNameBreakLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Rod Fish.
        /// </summary>
        internal static string FishNameBreakRod {
            get {
                return ResourceManager.GetString("FishNameBreakRod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mob (_{0}_).
        /// </summary>
        internal static string FishNameFormatMob {
            get {
                return ResourceManager.GetString("FishNameFormatMob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored Item.
        /// </summary>
        internal static string FishNameIgnoredItem {
            get {
                return ResourceManager.GetString("FishNameIgnoredItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored Large Fish.
        /// </summary>
        internal static string FishNameIgnoredLarge {
            get {
                return ResourceManager.GetString("FishNameIgnoredLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored Monster.
        /// </summary>
        internal static string FishNameIgnoredMonster {
            get {
                return ResourceManager.GetString("FishNameIgnoredMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored Small Fish.
        /// </summary>
        internal static string FishNameIgnoredSmall {
            get {
                return ResourceManager.GetString("FishNameIgnoredSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lack Skill Fish.
        /// </summary>
        internal static string FishNameLackSkill {
            get {
                return ResourceManager.GetString("FishNameLackSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost The Catch.
        /// </summary>
        internal static string FishNameLostCatch {
            get {
                return ResourceManager.GetString("FishNameLostCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster.
        /// </summary>
        internal static string FishNameMonster {
            get {
                return ResourceManager.GetString("FishNameMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Chart Box.
        /// </summary>
        internal static string FishNameQuestBox {
            get {
                return ResourceManager.GetString("FishNameQuestBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Large Fish.
        /// </summary>
        internal static string FishNameTooLarge {
            get {
                return ResourceManager.GetString("FishNameTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Small Fish.
        /// </summary>
        internal static string FishNameTooSmall {
            get {
                return ResourceManager.GetString("FishNameTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string FishNameUnknown {
            get {
                return ResourceManager.GetString("FishNameUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;.
        /// </summary>
        internal static string FormatQuoteArg {
            get {
                return ResourceManager.GetString("FormatQuoteArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string GUIButtonStart {
            get {
                return ResourceManager.GetString("GUIButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        internal static string GUIButtonStop {
            get {
                return ResourceManager.GetString("GUIButtonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Window.
        /// </summary>
        internal static string GUIChatDetectActionFlash {
            get {
                return ResourceManager.GetString("GUIChatDetectActionFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note On Tab.
        /// </summary>
        internal static string GUIChatDetectActionNote {
            get {
                return ResourceManager.GetString("GUIChatDetectActionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Fishing.
        /// </summary>
        internal static string GUIChatDetectActionStop {
            get {
                return ResourceManager.GetString("GUIChatDetectActionStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell.
        /// </summary>
        internal static string GUIChatDetectTypeLinkshell {
            get {
                return ResourceManager.GetString("GUIChatDetectTypeLinkshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        internal static string GUIChatDetectTypeParty {
            get {
                return ResourceManager.GetString("GUIChatDetectTypeParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say.
        /// </summary>
        internal static string GUIChatDetectTypeSay {
            get {
                return ResourceManager.GetString("GUIChatDetectTypeSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell.
        /// </summary>
        internal static string GUIChatDetectTypeTell {
            get {
                return ResourceManager.GetString("GUIChatDetectTypeTell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  LS (!!!).
        /// </summary>
        internal static string GUIChatTabAlertLinkshell {
            get {
                return ResourceManager.GetString("GUIChatTabAlertLinkshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  PT (!!!).
        /// </summary>
        internal static string GUIChatTabAlertParty {
            get {
                return ResourceManager.GetString("GUIChatTabAlertParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Say (!!!).
        /// </summary>
        internal static string GUIChatTabAlertSay {
            get {
                return ResourceManager.GetString("GUIChatTabAlertSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Tell (!!!).
        /// </summary>
        internal static string GUIChatTabAlertTell {
            get {
                return ResourceManager.GetString("GUIChatTabAlertTell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LS.
        /// </summary>
        internal static string GUIChatTabLinkshell {
            get {
                return ResourceManager.GetString("GUIChatTabLinkshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT.
        /// </summary>
        internal static string GUIChatTabParty {
            get {
                return ResourceManager.GetString("GUIChatTabParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say.
        /// </summary>
        internal static string GUIChatTabSay {
            get {
                return ResourceManager.GetString("GUIChatTabSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell.
        /// </summary>
        internal static string GUIChatTabTell {
            get {
                return ResourceManager.GetString("GUIChatTabTell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [{0}.{1} total skillups].
        /// </summary>
        internal static string GUIFormatLblSkillTotal {
            get {
                return ResourceManager.GetString("GUIFormatLblSkillTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1} ({2} released).
        /// </summary>
        internal static string GUIFormatNoCatch {
            get {
                return ResourceManager.GetString("GUIFormatNoCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0} Log.
        /// </summary>
        internal static string GUIFormatSaveLog {
            get {
                return ResourceManager.GetString("GUIFormatSaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1}/{2}, {3}, {4}:{5}, {6} Moon ({7}%).
        /// </summary>
        internal static string GUIFormatVanaTime {
            get {
                return ResourceManager.GetString("GUIFormatVanaTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bait equipped!.
        /// </summary>
        internal static string GUILblBaitNone {
            get {
                return ResourceManager.GetString("GUILblBaitNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rod equipped!.
        /// </summary>
        internal static string GUILblRodNone {
            get {
                return ResourceManager.GetString("GUILblRodNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Logs.
        /// </summary>
        internal static string GUISaveLogs {
            get {
                return ResourceManager.GetString("GUISaveLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Base Filename.
        /// </summary>
        internal static string GUISaveLogsTitle {
            get {
                return ResourceManager.GetString("GUISaveLogsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich Text Format.
        /// </summary>
        internal static string GUISaveRichText {
            get {
                return ResourceManager.GetString("GUISaveRichText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain UTF-8 Text.
        /// </summary>
        internal static string GUISaveUTF8Text {
            get {
                return ResourceManager.GetString("GUISaveUTF8Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_play {
            get {
                object obj = ResourceManager.GetObject("icon_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_stop {
            get {
                object obj = ResourceManager.GetObject("icon_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading fish updates..
        /// </summary>
        internal static string MessageDBErrorDownload {
            get {
                return ResourceManager.GetString("MessageDBErrorDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error doing database sync..
        /// </summary>
        internal static string MessageDBErrorGeneral {
            get {
                return ResourceManager.GetString("MessageDBErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading fish changes..
        /// </summary>
        internal static string MessageDBErrorUpload {
            get {
                return ResourceManager.GetString("MessageDBErrorUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting fish updates from XML..
        /// </summary>
        internal static string MessageDBErrorXML {
            get {
                return ResourceManager.GetString("MessageDBErrorXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database sync finished..
        /// </summary>
        internal static string MessageDBSyncFinish {
            get {
                return ResourceManager.GetString("MessageDBSyncFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning database sync..
        /// </summary>
        internal static string MessageDBSyncStart {
            get {
                return ResourceManager.GetString("MessageDBSyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: .
        /// </summary>
        internal static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please run FishingForm.exe as an Administrator..
        /// </summary>
        internal static string MessageErrorAdministratorNeeded {
            get {
                return ResourceManager.GetString("MessageErrorAdministratorNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFACE.dll was not found in the program&apos;s directory!.
        /// </summary>
        internal static string MessageErrorFFACEMissing {
            get {
                return ResourceManager.GetString("MessageErrorFFACEMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: {0}.
        /// </summary>
        internal static string MessageFormatError {
            get {
                return ResourceManager.GetString("MessageFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info: {0}.
        /// </summary>
        internal static string MessageFormatInfo {
            get {
                return ResourceManager.GetString("MessageFormatInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: {0}.
        /// </summary>
        internal static string MessageFormatWarning {
            get {
                return ResourceManager.GetString("MessageFormatWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info: .
        /// </summary>
        internal static string MessageInfo {
            get {
                return ResourceManager.GetString("MessageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to reset the settings?.
        /// </summary>
        internal static string MessageSettingsReset {
            get {
                return ResourceManager.GetString("MessageSettingsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to save the current settings?.
        /// </summary>
        internal static string MessageSettingsSave {
            get {
                return ResourceManager.GetString("MessageSettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FishingForm Error.
        /// </summary>
        internal static string MessageTitleFishingFormError {
            get {
                return ResourceManager.GetString("MessageTitleFishingFormError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Sync?.
        /// </summary>
        internal static string MessageTitleForceSync {
            get {
                return ResourceManager.GetString("MessageTitleForceSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Option Settings.
        /// </summary>
        internal static string MessageTitleSettingsReset {
            get {
                return ResourceManager.GetString("MessageTitleSettingsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Option Settings.
        /// </summary>
        internal static string MessageTitleSettingsSave {
            get {
                return ResourceManager.GetString("MessageTitleSettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string MessageTitleSyncFormError {
            get {
                return ResourceManager.GetString("MessageTitleSyncFormError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string MessageTitleSyncFormInfo {
            get {
                return ResourceManager.GetString("MessageTitleSyncFormInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        internal static string MessageTitleSyncFormWarning {
            get {
                return ResourceManager.GetString("MessageTitleSyncFormWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        internal static string MessageTitleWarning {
            get {
                return ResourceManager.GetString("MessageTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: .
        /// </summary>
        internal static string MessageWarning {
            get {
                return ResourceManager.GetString("MessageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windower path could not be found.
        /// </summary>
        internal static string PathWindowerResourcesError {
            get {
                return ResourceManager.GetString("PathWindowerResourcesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugins.
        /// </summary>
        internal static string PathWindowerResourcesFolder {
            get {
                return ResourceManager.GetString("PathWindowerResourcesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Char similar to ..
        /// </summary>
        internal static char Period {
            get {
                object obj = ResourceManager.GetObject("Period", resourceCulture);
                return ((char)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        /// </summary>
        internal static string QuoteMark {
            get {
                return ResourceManager.GetString("QuoteMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1.
        /// </summary>
        internal static string RegexGroup1 {
            get {
                return ResourceManager.GetString("RegexGroup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;.
        /// </summary>
        internal static string Semicolon {
            get {
                return ResourceManager.GetString("Semicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Char similar to  .
        /// </summary>
        internal static char SpaceChar {
            get {
                object obj = ResourceManager.GetObject("SpaceChar", resourceCulture);
                return ((char)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to FishDB MySQL server. Error number {0}.
        /// </summary>
        internal static string SQLMessageErrorCouldntConnect {
            get {
                return ResourceManager.GetString("SQLMessageErrorCouldntConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting program version status..
        /// </summary>
        internal static string SQLMessageErrorGettingVersion {
            get {
                return ResourceManager.GetString("SQLMessageErrorGettingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting new version message..
        /// </summary>
        internal static string SQLMessageErrorGettingVersionMessage {
            get {
                return ResourceManager.GetString("SQLMessageErrorGettingVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting Newest DB Modification Time.
        /// </summary>
        internal static string SQLMessageErrorNewestModTime {
            get {
                return ResourceManager.GetString("SQLMessageErrorNewestModTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to FishDB MySQL server. Please contact program maintainer..
        /// </summary>
        internal static string SQLMessageErrorNoConnection {
            get {
                return ResourceManager.GetString("SQLMessageErrorNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading fish.
        /// </summary>
        internal static string SQLMessageErrorUploading {
            get {
                return ResourceManager.GetString("SQLMessageErrorUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding bait &quot;{0}&quot; to fish &quot;{1}&quot;.
        /// </summary>
        internal static string SQLMessageFormatErrorAddingBaitFish {
            get {
                return ResourceManager.GetString("SQLMessageFormatErrorAddingBaitFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding new fish &quot;{0}&quot;.
        /// </summary>
        internal static string SQLMessageFormatErrorAddingFish {
            get {
                return ResourceManager.GetString("SQLMessageFormatErrorAddingFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding zone &quot;{0}&quot; to fish &quot;{1}&quot;.
        /// </summary>
        internal static string SQLMessageFormatErrorAddingZoneFish {
            get {
                return ResourceManager.GetString("SQLMessageFormatErrorAddingZoneFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading new fish for {0}.
        /// </summary>
        internal static string SQLMessageFormatErrorDownloadingFishRod {
            get {
                return ResourceManager.GetString("SQLMessageFormatErrorDownloadingFishRod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading renames for {0}.
        /// </summary>
        internal static string SQLMessageFormatErrorDownloadingRenameRod {
            get {
                return ResourceManager.GetString("SQLMessageFormatErrorDownloadingRenameRod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting fish ID from DB for &quot;{0}&quot;.
        /// </summary>
        internal static string SQLMessageFormatErrorGettingFishID {
            get {
                return ResourceManager.GetString("SQLMessageFormatErrorGettingFishID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting new fish &quot;{0}&quot; with IDs: {1}, {2}, {3}.
        /// </summary>
        internal static string SQLMessageFormatErrorGettingNewFishWithIDs {
            get {
                return ResourceManager.GetString("SQLMessageFormatErrorGettingNewFishWithIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting renamed fish &quot;{0}&quot; to &quot;{1}&quot; with IDs: {2}, {3}, {4}.
        /// </summary>
        internal static string SQLMessageFormatErrorGettingRenamedFishWithIDs {
            get {
                return ResourceManager.GetString("SQLMessageFormatErrorGettingRenamedFishWithIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error renaming fish &quot;{0}&quot; to &quot;{1}&quot;.
        /// </summary>
        internal static string SQLMessageFormatErrorRenamingFish {
            get {
                return ResourceManager.GetString("SQLMessageFormatErrorRenamingFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading bait and zones for fish &quot;{0}&quot; for {1}..
        /// </summary>
        internal static string SQLMessageFormatErrorUploadingBaitZones {
            get {
                return ResourceManager.GetString("SQLMessageFormatErrorUploadingBaitZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading fish &quot;{0}&quot; for {1}..
        /// </summary>
        internal static string SQLMessageFormatErrorUploadingFishRod {
            get {
                return ResourceManager.GetString("SQLMessageFormatErrorUploadingFishRod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading rename from &quot;{0}&quot; to &quot;{1}&quot; for {2}..
        /// </summary>
        internal static string SQLMessageFormatErrorUploadingRename {
            get {
                return ResourceManager.GetString("SQLMessageFormatErrorUploadingRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload to DB finished..
        /// </summary>
        internal static string SQLMessageUploadFinished {
            get {
                return ResourceManager.GetString("SQLMessageUploadFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting upload to DB..
        /// </summary>
        internal static string SQLMessageUploadStart {
            get {
                return ResourceManager.GetString("SQLMessageUploadStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking program version..
        /// </summary>
        internal static string SQLMessageVersionCheck {
            get {
                return ResourceManager.GetString("SQLMessageVersionCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for version update message..
        /// </summary>
        internal static string SQLMessageVersionMessageCheck {
            get {
                return ResourceManager.GetString("SQLMessageVersionMessageCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not close connection..
        /// </summary>
        internal static string SQLMessageWarningCloseConnection {
            get {
                return ResourceManager.GetString("SQLMessageWarningCloseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, you cannot fish..
        /// </summary>
        internal static string StatusErrorCantFish {
            get {
                return ResourceManager.GetString("StatusErrorCantFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal chat log error, attempting to recover..
        /// </summary>
        internal static string StatusErrorChatGet {
            get {
                return ResourceManager.GetString("StatusErrorChatGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell chat received!.
        /// </summary>
        internal static string StatusErrorChatLinkshell {
            get {
                return ResourceManager.GetString("StatusErrorChatLinkshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party chat received!.
        /// </summary>
        internal static string StatusErrorChatParty {
            get {
                return ResourceManager.GetString("StatusErrorChatParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say chat received!.
        /// </summary>
        internal static string StatusErrorChatSay {
            get {
                return ResourceManager.GetString("StatusErrorChatSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell received!.
        /// </summary>
        internal static string StatusErrorChatTell {
            get {
                return ResourceManager.GetString("StatusErrorChatTell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory is full!.
        /// </summary>
        internal static string StatusErrorFullInventory {
            get {
                return ResourceManager.GetString("StatusErrorFullInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GM] DETECTED!!!.
        /// </summary>
        internal static string StatusErrorGM {
            get {
                return ResourceManager.GetString("StatusErrorGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing/Sitting, please stand..
        /// </summary>
        internal static string StatusErrorHealing {
            get {
                return ResourceManager.GetString("StatusErrorHealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle..
        /// </summary>
        internal static string StatusErrorIdle {
            get {
                return ResourceManager.GetString("StatusErrorIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory might be full..
        /// </summary>
        internal static string StatusErrorInventoryProblem {
            get {
                return ResourceManager.GetString("StatusErrorInventoryProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown destination to move fish..
        /// </summary>
        internal static string StatusErrorItemizerDestination {
            get {
                return ResourceManager.GetString("StatusErrorItemizerDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown itemizer/itemtools command..
        /// </summary>
        internal static string StatusErrorItemizerUnknown {
            get {
                return ResourceManager.GetString("StatusErrorItemizerUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not fishing because character is not logged in..
        /// </summary>
        internal static string StatusErrorLoggedOut {
            get {
                return ResourceManager.GetString("StatusErrorLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster caught!!!.
        /// </summary>
        internal static string StatusErrorMonster {
            get {
                return ResourceManager.GetString("StatusErrorMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to a fishing position..
        /// </summary>
        internal static string StatusErrorMovePlayer {
            get {
                return ResourceManager.GetString("StatusErrorMovePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of bait..
        /// </summary>
        internal static string StatusErrorNoBait {
            get {
                return ResourceManager.GetString("StatusErrorNoBait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rod or bait equipped or set in options..
        /// </summary>
        internal static string StatusErrorNoBaitOrRodEquipped {
            get {
                return ResourceManager.GetString("StatusErrorNoBaitOrRodEquipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your rod is broken..
        /// </summary>
        internal static string StatusErrorRodBroken {
            get {
                return ResourceManager.GetString("StatusErrorRodBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing skill cap reached..
        /// </summary>
        internal static string StatusErrorSkillCapped {
            get {
                return ResourceManager.GetString("StatusErrorSkillCapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough MP to cast Sneak..
        /// </summary>
        internal static string StatusErrorSneakLackMP {
            get {
                return ResourceManager.GetString("StatusErrorSneakLackMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not fishing for unknown reason..
        /// </summary>
        internal static string StatusErrorUnknown {
            get {
                return ResourceManager.GetString("StatusErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed zones!.
        /// </summary>
        internal static string StatusErrorZoneChanged {
            get {
                return ResourceManager.GetString("StatusErrorZoneChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoned while catching a fish..
        /// </summary>
        internal static string StatusErrorZoned {
            get {
                return ResourceManager.GetString("StatusErrorZoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatigue limit reached: Max catch limit..
        /// </summary>
        internal static string StatusFatiguedMaxCatchLimit {
            get {
                return ResourceManager.GetString("StatusFatiguedMaxCatchLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatigue limit reached: Max no catches..
        /// </summary>
        internal static string StatusFatigueNoCatches {
            get {
                return ResourceManager.GetString("StatusFatigueNoCatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casting a {0} [{1}]..
        /// </summary>
        internal static string StatusFormatCastingBait {
            get {
                return ResourceManager.GetString("StatusFormatCastingBait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casting in {0} seconds..
        /// </summary>
        internal static string StatusFormatCastingSeconds {
            get {
                return ResourceManager.GetString("StatusFormatCastingSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faking {0}..
        /// </summary>
        internal static string StatusFormatFakingFish {
            get {
                return ResourceManager.GetString("StatusFormatFakingFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighting {0}..
        /// </summary>
        internal static string StatusFormatFightingFish {
            get {
                return ResourceManager.GetString("StatusFormatFightingFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killing {0} in {1} seconds..
        /// </summary>
        internal static string StatusFormatKillingFish {
            get {
                return ResourceManager.GetString("StatusFormatKillingFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished moving {0} to case..
        /// </summary>
        internal static string StatusFormatMoveCaseFinished {
            get {
                return ResourceManager.GetString("StatusFormatMoveCaseFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished moving {0} to sack..
        /// </summary>
        internal static string StatusFormatMoveSackFinished {
            get {
                return ResourceManager.GetString("StatusFormatMoveSackFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished moving {0} to satchel..
        /// </summary>
        internal static string StatusFormatMoveSatchelFinished {
            get {
                return ResourceManager.GetString("StatusFormatMoveSatchelFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving {0} to case: {1} remaining..
        /// </summary>
        internal static string StatusFormatMoveToCase {
            get {
                return ResourceManager.GetString("StatusFormatMoveToCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving {0} to sack: {1} remaining..
        /// </summary>
        internal static string StatusFormatMoveToSack {
            get {
                return ResourceManager.GetString("StatusFormatMoveToSack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving {0} to satchel: {1} remaining..
        /// </summary>
        internal static string StatusFormatMoveToSatchel {
            get {
                return ResourceManager.GetString("StatusFormatMoveToSatchel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No catch..
        /// </summary>
        internal static string StatusFormatNoCatchFirst {
            get {
                return ResourceManager.GetString("StatusFormatNoCatchFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No catch, {0} in a row..
        /// </summary>
        internal static string StatusFormatNoCatchNumber {
            get {
                return ResourceManager.GetString("StatusFormatNoCatchNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reeling in {0}..
        /// </summary>
        internal static string StatusFormatReelingFish {
            get {
                return ResourceManager.GetString("StatusFormatReelingFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releasing {0}..
        /// </summary>
        internal static string StatusFormatReleaseFish {
            get {
                return ResourceManager.GetString("StatusFormatReleaseFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding one second to cast times..
        /// </summary>
        internal static string StatusInfoAddTime {
            get {
                return ResourceManager.GetString("StatusInfoAddTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of bait: Logging out..
        /// </summary>
        internal static string StatusInfoBaitLogout {
            get {
                return ResourceManager.GetString("StatusInfoBaitLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of bait: Shutting down..
        /// </summary>
        internal static string StatusInfoBaitShutdown {
            get {
                return ResourceManager.GetString("StatusInfoBaitShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of bait: Warping..
        /// </summary>
        internal static string StatusInfoBaitWarping {
            get {
                return ResourceManager.GetString("StatusInfoBaitWarping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Fisherman&apos;s belt..
        /// </summary>
        internal static string StatusInfoEnchantBelt {
            get {
                return ResourceManager.GetString("StatusInfoEnchantBelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using left ring ({0})..
        /// </summary>
        internal static string StatusInfoEnchantLRing {
            get {
                return ResourceManager.GetString("StatusInfoEnchantLRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using right ring ({0})..
        /// </summary>
        internal static string StatusInfoEnchantRRing {
            get {
                return ResourceManager.GetString("StatusInfoEnchantRRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip a rod / bait to refresh lists..
        /// </summary>
        internal static string StatusInfoEquipToRefresh {
            get {
                return ResourceManager.GetString("StatusInfoEquipToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatigue limit reached: Logging out..
        /// </summary>
        internal static string StatusInfoFatiguedLogout {
            get {
                return ResourceManager.GetString("StatusInfoFatiguedLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatigue limit reached: Shutting down..
        /// </summary>
        internal static string StatusInfoFatiguedShutdown {
            get {
                return ResourceManager.GetString("StatusInfoFatiguedShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatigue limit reached: Warping..
        /// </summary>
        internal static string StatusInfoFatiguedWarping {
            get {
                return ResourceManager.GetString("StatusInfoFatiguedWarping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case is full..
        /// </summary>
        internal static string StatusInfoFullCase {
            get {
                return ResourceManager.GetString("StatusInfoFullCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running full inventory command..
        /// </summary>
        internal static string StatusInfoFullInventoryCommand {
            get {
                return ResourceManager.GetString("StatusInfoFullInventoryCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory is full: Logging out..
        /// </summary>
        internal static string StatusInfoFullInventoryLogout {
            get {
                return ResourceManager.GetString("StatusInfoFullInventoryLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory is full: Shutting down..
        /// </summary>
        internal static string StatusInfoFullInventoryShutdown {
            get {
                return ResourceManager.GetString("StatusInfoFullInventoryShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory is full: Warping..
        /// </summary>
        internal static string StatusInfoFullInventoryWarp {
            get {
                return ResourceManager.GetString("StatusInfoFullInventoryWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sack is full..
        /// </summary>
        internal static string StatusInfoFullSack {
            get {
                return ResourceManager.GetString("StatusInfoFullSack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satchel is full..
        /// </summary>
        internal static string StatusInfoFullSatchel {
            get {
                return ResourceManager.GetString("StatusInfoFullSatchel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanted / Unwanted lists refreshed..
        /// </summary>
        internal static string StatusInfoListsRefreshed {
            get {
                return ResourceManager.GetString("StatusInfoListsRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No FFXI process available..
        /// </summary>
        internal static string StatusInfoNoProcess {
            get {
                return ResourceManager.GetString("StatusInfoNoProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reattached to process, attempting to restart fishing..
        /// </summary>
        internal static string StatusInfoReattachedRestart {
            get {
                return ResourceManager.GetString("StatusInfoReattachedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reattached to process after chat error, ready to fish..
        /// </summary>
        internal static string StatusInfoReattachSuccess {
            get {
                return ResourceManager.GetString("StatusInfoReattachSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your rod is broken. Attempting to re-equip..
        /// </summary>
        internal static string StatusInfoRodBroken {
            get {
                return ResourceManager.GetString("StatusInfoRodBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for a bite..
        /// </summary>
        internal static string StatusInfoWaitBite {
            get {
                return ResourceManager.GetString("StatusInfoWaitBite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s fishing skill.
        /// </summary>
        internal static string TestChatFishingSkill {
            get {
                return ResourceManager.GetString("TestChatFishingSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points..
        /// </summary>
        internal static string TestChatFishingSkillPoints {
            get {
                return ResourceManager.GetString("TestChatFishingSkillPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
